on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: List secrets in cred
        run: 'op item list --vault Test --format json | op item get - --format json'
