on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Load secret
        id: op-load-secret
        uses: passportxyz/load-secrets-action@load-all
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Print masked secret
        run: 'echo "Secret: ${{ steps.op-load-secret.outputs.SECRET }}"'
